# Generated by Django 5.2.14 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='meetings/original/')),
                ('audio_file', models.FileField(upload_to='meetings/audio/')),
                ('transcript_file', models.FileField(upload_to='meetings/transcripts/')),
                ('provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('meeting_type', models.CharField(blank=True, max_length=100)),
                ('transcript', models.TextField()),
                ('ai_report', models.TextField()),
                ('duration', models.FloatField()),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
