# Generated by Django 5.2.17 on 2026-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_aisettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='gemini_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='stage',
            field=models.CharField(default='queued', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
